# Generated by Django 2.0.13 on 2019-10-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191003_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sakura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sakura', models.IntegerField()),
                ('sumire', models.IntegerField()),
                ('maria', models.IntegerField()),
                ('iris', models.IntegerField()),
                ('koran', models.IntegerField()),
                ('kanna', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Name',
        ),
    ]
