# Generated by Django 2.0.13 on 2019-10-22 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20191010_2232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sakura',
        ),
        migrations.RemoveField(
            model_name='group',
            name='number',
        ),
    ]
