# Generated by Django 2.0.13 on 2019-10-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20191022_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='route',
            name='minute',
        ),
        migrations.AlterField(
            model_name='group',
            name='destination',
            field=models.CharField(choices=[('あり', 'あり'), ('なし', 'なし')], max_length=10),
        ),
        migrations.AlterField(
            model_name='group',
            name='exitmark',
            field=models.CharField(blank=True, choices=[('出口1', '出口１')], max_length=20),
        ),
        migrations.AlterField(
            model_name='group',
            name='landmark',
            field=models.CharField(blank=True, choices=[('都庁', '都庁'), ('新宿ピカデリー', '新宿ピカデリー')], max_length=20),
        ),
        migrations.AlterField(
            model_name='group',
            name='people',
            field=models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='route',
            name='route',
            field=models.CharField(choices=[('中央線', '中央線'), ('山の手線', '山の手線'), ('西武新宿線', '西武新宿線')], max_length=20),
        ),
    ]
