# Generated by Django 2.0.13 on 2019-10-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20191022_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='number',
            field=models.IntegerField(),
        ),
    ]
