# Generated by Django 2.2.7 on 2019-12-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20191219_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='landmark',
            field=models.CharField(choices=[('新宿サザンテラス', '新宿サザンテラス'), ('aaa', 'bbb')], default='-----', max_length=100),
        ),
    ]
