# Generated by Django 2.2.7 on 2019-12-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20191219_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='landmark',
            field=models.CharField(choices=[('新宿szn', '新宿サザンテラス'), ('a', 'aaa')], default='-----', max_length=100),
        ),
    ]
